using System;
using System.Collections.Generic;
using UnityEngine;

/// <summary>
/// Immutable data record for one network packet in the Packet Filter puzzle.
///
/// Payload is always stored in full internally. The UI controls whether to
/// display it (Phase 1) or show "[TLS ENCRYPTED]" (Phase 2). Phase 3 rule
/// evaluation always matches against the real payload, so "payload:ARBITEX_CMD"
/// works even though the player never saw the payload in Phase 2.
/// </summary>
[Serializable]
public class PacketData
{
    public string Timestamp;
    public string SrcIp;
    public string DstIp;
    public string Proto;          // "TCP", "UDP", "ICMP"
    public int    DstPort;        // 0 for ICMP
    public string Payload;

    public bool   IsMalicious;
    public string C2Channel;      // null = legitimate; "C2-01" etc for C2 packets

    // True for legitimate services that share a port or protocol with a C2 channel.
    // Broad rules that block these count as collateral damage.
    public bool   IsCollateralRisk;
    public string ServiceName;    // e.g. "Network Monitor" -- only if IsCollateralRisk
}

/// <summary>
/// A legitimate service at risk of collateral blocking. Used in Phase 3 feedback.
/// </summary>
[Serializable]
public class CollateralService
{
    public string Name;
    public string OverlapNote;    // e.g. "shares port :4444 with C2-01/02"
}

/// <summary>
/// Complete scenario data for one puzzle attempt, generated by
/// PacketFilterPuzzleUI.BuildScenario(tier).
/// </summary>
public class PacketFilterScenario
{
    public List<PacketData>        LogPackets   = new List<PacketData>();   // Phase 1 log
    public List<PacketData>        LivePackets  = new List<PacketData>();   // Phase 2 stream
    public List<string>            C2Channels   = new List<string>();       // channel IDs to block
    public List<CollateralService> Services     = new List<CollateralService>(); // at-risk services
    public float                   PacketInterval;  // Phase 2 spawn rate (seconds)
    public float                   PacketExpiry;    // 0 = no expiry; >0 = Tier 4 auto-allow
    public bool                    HasDecoyRules;   // Tier 4 pre-filled trap rules
}
